fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:  '4.0.0'
    limits: 'git@github.com:saz/puppet-limits.git'
    augeasproviders: 'git@github.com:hercules-team/augeasproviders.git'
  symlinks:
    port389: "#{source_dir}"
