fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:  '4.0.0'
    limits: 'https://github.com/saz/puppet-limits.git'
    augeasproviders: 'https://github.com/hercules-team/augeasproviders.git'
    openldap: 'https://github.com/mcanevet/puppet-openldap.git'
    nssdb:
      repo: 'https://github.com/jhoblitt/puppet-nssdb.git'
      ref:  '1be003431c3f612483756a26eebf13cfa14d18a9'
  symlinks:
    port389: "#{source_dir}"
