fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:  '4.0.0'
    limits: 'https://github.com/saz/puppet-limits.git'
    augeasproviders: 'https://github.com/hercules-team/augeasproviders.git'
  symlinks:
    port389: "#{source_dir}"
